// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0vXPKH8bRmtVmGPOyETuONqkRK5mXK5o',
    appId: '1:741551928272:web:12da1776350262e5cc3fd5',
    messagingSenderId: '741551928272',
    projectId: 'ride-userapp',
    authDomain: 'ride-userapp.firebaseapp.com',
    storageBucket: 'ride-userapp.firebasestorage.app',
    measurementId: 'G-6JE3P9T0JE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAil95N9fIYePlEn4rmhmqrx7Qv18C7iZM',
    appId: '1:741551928272:android:aa43aab723216b7ecc3fd5',
    messagingSenderId: '741551928272',
    projectId: 'ride-userapp',
    storageBucket: 'ride-userapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDR1gBcx5R-QQ_Y01eG3alOZjaZ6hVzQWA',
    appId: '1:741551928272:ios:e87b485f19b45c1dcc3fd5',
    messagingSenderId: '741551928272',
    projectId: 'ride-userapp',
    storageBucket: 'ride-userapp.firebasestorage.app',
    iosBundleId: 'com.example.rideUserappFixed',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDR1gBcx5R-QQ_Y01eG3alOZjaZ6hVzQWA',
    appId: '1:741551928272:ios:e87b485f19b45c1dcc3fd5',
    messagingSenderId: '741551928272',
    projectId: 'ride-userapp',
    storageBucket: 'ride-userapp.firebasestorage.app',
    iosBundleId: 'com.example.rideUserappFixed',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB0vXPKH8bRmtVmGPOyETuONqkRK5mXK5o',
    appId: '1:741551928272:web:09fe295954221f8ecc3fd5',
    messagingSenderId: '741551928272',
    projectId: 'ride-userapp',
    authDomain: 'ride-userapp.firebaseapp.com',
    storageBucket: 'ride-userapp.firebasestorage.app',
    measurementId: 'G-M12HT53DBG',
  );
}
